# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 19:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('waste_schedule', '0012_auto_20170503_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledetail',
            name='waste_area_ids',
            field=models.CharField(blank=True, max_length=1028, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Waste area(s) effected'),
        ),
    ]
