# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-03 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_schedule', '0014_auto_20171201_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledetail',
            name='description',
            field=models.CharField(max_length=512, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='scheduledetail',
            name='note',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Note'),
        ),
    ]
