# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_cache', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='Username')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
                ('referer', models.CharField(max_length=64, verbose_name='Referer')),
                ('url', models.CharField(max_length=256, verbose_name='Authentication URL')),
            ],
        ),
        migrations.AddField(
            model_name='datasource',
            name='credentials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_cache.DataCredentials'),
        ),
    ]
