# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('data_cache', '0002_auto_20171002_1537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataCredentials',
            new_name='DataCredential',
        ),
    ]
