# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_cache', '0003_auto_20171003_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='url',
            field=models.CharField(max_length=1024, null=True, verbose_name='Data Source URL'),
        ),
    ]
