# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_cache', '0004_auto_20171009_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='datavalue',
            name='param',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_cache.DataCredential'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='url',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Data Source URL'),
        ),
    ]
