# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_cache', '0005_auto_20171018_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='data_id_parse_path',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Data ID to extract'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='data_parse_path',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Data to extract'),
        ),
    ]
