# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_cache', '0006_auto_20171018_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datavalue',
            name='param',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
