# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_cache', '0007_auto_20171018_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='url',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Data Source URL'),
        ),
    ]
