# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_cache', '0009_auto_20171101_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Name'),
        ),
    ]
