# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_cache', '0010_auto_20171102_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCitySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('description', models.CharField(max_length=1024, verbose_name='name')),
                ('url', models.CharField(blank=True, max_length=2056, null=True, verbose_name='url')),
                ('credentials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_cache.DataCredential')),
                ('data_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_cache.DataSet')),
            ],
        ),
    ]
