# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_cache', '0011_datacitysummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacitysummary',
            options={'verbose_name_plural': 'data city summaries'},
        ),
        migrations.AlterField(
            model_name='datacitysummary',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='description'),
        ),
    ]
