# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-09 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_cache', '0012_auto_20180108_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDescriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor_type', models.CharField(max_length=64, verbose_name='Descriptor type')),
                ('value', models.CharField(max_length=64, verbose_name='value')),
            ],
        ),
        migrations.AlterModelOptions(
            name='datacitysummary',
            options={'ordering': ['name'], 'verbose_name_plural': 'data city summaries'},
        ),
        migrations.AddField(
            model_name='datacitysummary',
            name='descriptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_cache.DataDescriptor'),
        ),
    ]
