# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_cache', '0013_auto_20180109_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datadescriptor',
            options={'ordering': ['descriptor_type', 'value']},
        ),
        migrations.AddField(
            model_name='datasource',
            name='where',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Where clause'),
        ),
        migrations.AlterField(
            model_name='datadescriptor',
            name='descriptor_type',
            field=models.CharField(choices=[('department', 'Department'), ('boundary', 'Boundary')], default='department', max_length=64, verbose_name='Type'),
        ),
    ]
