# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_cache', '0014_auto_20180110_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasource',
            old_name='where',
            new_name='socrata_where',
        ),
    ]
