# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_cache', '0015_auto_20180110_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTEActiveGasSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_partner', models.CharField(db_index=True, max_length=128, verbose_name='Business Partner')),
                ('contract_account', models.BigIntegerField(verbose_name='Contract Account')),
                ('installation_number', models.BigIntegerField(verbose_name='Installation Number')),
                ('contract_number', models.BigIntegerField(verbose_name='Contract Number')),
                ('connection_object', models.BigIntegerField(verbose_name='Connection Object')),
                ('premise', models.BigIntegerField(verbose_name='Premise')),
                ('house_number', models.IntegerField(verbose_name='House Number')),
                ('street', models.CharField(db_index=True, max_length=128, verbose_name='Street')),
                ('secondary_code', models.CharField(max_length=16, verbose_name='Secondary Code')),
                ('secondary_value', models.CharField(max_length=16, verbose_name='Secondary Value')),
                ('city', models.CharField(max_length=16, verbose_name='City')),
                ('postal_code', models.IntegerField(verbose_name='Postal Code')),
                ('active_date', models.DateField(verbose_name='Active Date')),
            ],
        ),
    ]
