# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_cache', '0016_dteactivegassites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dteactivegassites',
            name='house_number',
            field=models.CharField(help_text='Sometimes not numeric, e.g., "#"', max_length=32, verbose_name='House Number'),
        ),
    ]
