# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_cache', '0017_auto_20180111_1605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DTEActiveGasSites',
            new_name='DTEActiveGasSite',
        ),
    ]
