# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_cache', '0018_auto_20180111_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='dteactivegassite',
            name='full_street_address',
            field=models.CharField(db_index=True, default='', max_length=128, verbose_name='Street Address Combined'),
        ),
    ]
