# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_cache', '0019_dteactivegassite_full_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='dteactivegassite',
            name='parcel_id',
            field=models.CharField(default='', max_length=32, verbose_name='Parcel ID'),
        ),
    ]
