# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_cache', '0020_dteactivegassite_parcel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNNKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=256, verbose_name='Keyword')),
            ],
        ),
    ]
