# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import sqlserver_ado.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', sqlserver_ado.fields.BigAutoField(primary_key=True, serialize=False)),
                ('pnum', models.CharField(max_length=25)),
                ('unit', models.CharField(max_length=5)),
                ('status', models.SmallIntegerField()),
                ('salenum', models.SmallIntegerField()),
                ('saledate', models.DateTimeField(blank=True, null=True)),
                ('usecode', models.CharField(max_length=5, db_column='useCode')),
                ('saleprice', models.DecimalField(max_digits=18, decimal_places=0)),
                ('adjsaleprice', models.DecimalField(max_digits=18, decimal_places=0)),
                ('infadjsaleprice', models.DecimalField(max_digits=18, decimal_places=0)),
                ('reasonsforadj', models.CharField(max_length=24)),
                ('terms', models.CharField(max_length=20)),
                ('instr', models.CharField(max_length=3)),
                ('ltype', models.SmallIntegerField()),
                ('grantor', models.CharField(max_length=35)),
                ('grantorline2', models.CharField(max_length=35, db_column='grantorLine2')),
                ('grantee', models.CharField(max_length=35)),
                ('granteeline2', models.CharField(max_length=35, db_column='granteeLine2')),
                ('propclass', models.CharField(max_length=5)),
                ('ecftbl', models.CharField(max_length=5)),
                ('liberpage', models.CharField(max_length=20)),
                ('cmts', models.CharField(max_length=30)),
                ('confidential', models.SmallIntegerField()),
                ('verifiedby', models.CharField(max_length=14)),
                ('dontupdate', models.SmallIntegerField()),
                ('otherparcelsinsaleflag', models.SmallIntegerField()),
                ('otherparcelsinsale_0', models.CharField(max_length=25)),
                ('otherparcelsinsale_1', models.CharField(max_length=25)),
                ('otherparcelsinsale_2', models.CharField(max_length=25)),
                ('otherparcelsinsale_3', models.CharField(max_length=25)),
                ('otherparcelsinsale_4', models.CharField(max_length=25)),
                ('pertrans', models.DecimalField(max_digits=18, decimal_places=2)),
                ('affdate', models.DateTimeField(blank=True, null=True)),
                ('userstr', models.CharField(max_length=15)),
                ('usernum', models.SmallIntegerField()),
                ('streetnumber', models.FloatField()),
                ('streetdirect', models.CharField(max_length=2)),
                ('streetname', models.CharField(max_length=25)),
                ('unitorapt', models.CharField(max_length=7)),
                ('addresscombined', models.CharField(max_length=62)),
                ('notaff', models.SmallIntegerField(db_column='notAff')),
                ('ptafinebilled', models.SmallIntegerField(db_column='PTAFineBilled')),
                ('currentassment', models.FloatField()),
                ('previousassment', models.FloatField()),
                ('assmentwhensold', models.FloatField()),
                ('curassmentsaleratio', models.FloatField()),
                ('prevassmentsaleratio', models.FloatField()),
                ('assmentwhensoldsaleratio', models.FloatField()),
                ('esttcvsaleratio', models.FloatField()),
                ('filedate', models.DateTimeField(blank=True, null=True)),
                ('sendstatementto', models.SmallIntegerField()),
                ('esttcv', models.FloatField()),
                ('landvalue', models.FloatField()),
                ('totalacres', models.FloatField()),
                ('actualfront', models.FloatField()),
                ('efffront', models.FloatField()),
                ('avedepth', models.FloatField()),
                ('improved', models.SmallIntegerField()),
                ('landivalue', models.FloatField()),
                ('bldgimprval', models.FloatField()),
                ('resb_numresb', models.SmallIntegerField()),
                ('resb_occ', models.SmallIntegerField()),
                ('resb_styhgt', models.SmallIntegerField()),
                ('resb_yearbuilt', models.SmallIntegerField()),
                ('resb_bldgclass', models.SmallIntegerField()),
                ('resb_plusminus', models.SmallIntegerField()),
                ('resb_style', models.CharField(max_length=15)),
                ('resb_effage', models.SmallIntegerField()),
                ('resb_depr', models.SmallIntegerField()),
                ('resb_heat', models.SmallIntegerField()),
                ('resb_nbed', models.SmallIntegerField()),
                ('resb_fullbaths', models.SmallIntegerField()),
                ('resb_halfbaths', models.SmallIntegerField()),
                ('resb_gartype', models.SmallIntegerField(db_column='resb_garType')),
                ('resb_fireplaces', models.SmallIntegerField()),
                ('resb_exterior', models.SmallIntegerField()),
                ('resb_floorarea', models.IntegerField()),
                ('resb_groundarea', models.IntegerField()),
                ('resb_basementarea', models.IntegerField()),
                ('resb_garagearea', models.IntegerField()),
                ('resb_avestyht', models.FloatField()),
                ('resb_pricefloor', models.FloatField()),
                ('resb_priceground', models.FloatField()),
                ('resb_calcvalue', models.FloatField()),
                ('resb_value', models.FloatField()),
                ('cib_numcib', models.SmallIntegerField()),
                ('cib_occ', models.SmallIntegerField()),
                ('cib_yearbuilt', models.SmallIntegerField()),
                ('cib_bldgclass', models.SmallIntegerField()),
                ('cib_effage', models.SmallIntegerField()),
                ('cib_stories', models.SmallIntegerField()),
                ('cib_floorarea', models.FloatField()),
                ('cib_pricefloor', models.FloatField()),
                ('cib_calcvalue', models.FloatField()),
                ('cib_value', models.FloatField()),
                ('agb_numagb', models.SmallIntegerField()),
                ('agb_calcvalue', models.FloatField()),
                ('agb_value', models.FloatField()),
                ('nothomestead', models.SmallIntegerField(db_column='notHomestead')),
                ('pa260', models.SmallIntegerField()),
                ('grossrent', models.FloatField(db_column='GrossRent')),
                ('marknumber', models.IntegerField(db_column='markNumber')),
                ('netacres', models.DecimalField(max_digits=18, decimal_places=3, db_column='netAcres')),
                ('transdenial', models.SmallIntegerField(db_column='transDenial')),
                ('useinecf', models.SmallIntegerField(db_column='useInECF')),
                ('landtable', models.CharField(max_length=5, db_column='landTable')),
                ('sec108', models.IntegerField(db_column='Sec108')),
                ('dateedited', models.DateTimeField(blank=True, null=True, db_column='dateEdited')),
                ('streetsortstring', models.CharField(max_length=62, db_column='streetSortString')),
                ('unitclasssort', models.CharField(max_length=21, db_column='unitClassSort')),
                ('unitsaledatesort', models.CharField(max_length=23, db_column='unitSaleDateSort')),
                ('pnumsort', models.CharField(max_length=36, db_column='pnumSort')),
                ('saledatesort', models.CharField(max_length=10, db_column='saleDateSort')),
                ('granteesort', models.CharField(max_length=46, db_column='granteeSort')),
                ('grantorsort', models.CharField(max_length=46, db_column='grantorSort')),
                ('liberpagesort', models.CharField(max_length=31, db_column='liberPageSort')),
                ('unitecfsort', models.CharField(max_length=22, db_column='unitEcfSort')),
                ('salepricesort', models.CharField(max_length=30, db_column='salePriceSort')),
                ('unittermssort', models.CharField(max_length=36, db_column='unitTermsSort')),
                ('unitsaletypesort', models.CharField(max_length=18, db_column='unitSaleTypeSort')),
                ('unituserasort', models.CharField(max_length=32, db_column='unitUserASort')),
                ('classsort', models.CharField(max_length=16, db_column='classSort')),
                ('unitinstsort', models.CharField(max_length=19, db_column='unitInstSort')),
                ('usecodesort', models.CharField(max_length=16, db_column='useCodeSort')),
                ('unitlandsort', models.CharField(max_length=22, db_column='unitLandSort')),
                ('isvacantlandsale', models.SmallIntegerField(db_column='isVacantLandSale')),
                ('sdredemptiondate', models.DateTimeField(blank=True, null=True, db_column='sdRedemptionDate')),
                ('sduncappingdate', models.DateTimeField(blank=True, null=True, db_column='sdUncappingDate')),
                ('flagforecf', models.SmallIntegerField(db_column='flagForEcf')),
                ('sdredemptiondatesort', models.CharField(max_length=17, db_column='sdRedemptionDateSort')),
                ('sduncappingdatesort', models.CharField(max_length=17, db_column='sdUncappingDateSort')),
                ('ptapenaltyapplies', models.SmallIntegerField(db_column='PTAPenaltyApplies')),
                ('cibbedrooms', models.SmallIntegerField(db_column='CiBBedrooms')),
                ('cibunits', models.SmallIntegerField(db_column='CiBUnits')),
                ('sentdate', models.DateTimeField(blank=True, null=True, db_column='sentDate')),
                ('padatefiled', models.DateTimeField(blank=True, null=True, db_column='paDateFiled')),
                ('additionalgrantees', models.CharField(max_length=200, db_column='additionalGrantees')),
                ('additionalgrantors', models.CharField(max_length=200, db_column='additionalGrantors')),
                ('pa260liberpage', models.CharField(max_length=20, db_column='pa260LiberPage')),
                ('importstatus', models.CharField(max_length=30, db_column='importStatus')),
                ('ptaamountbilled', models.FloatField(db_column='ptaAmountBilled')),
                ('lifeleasegrantee', models.CharField(max_length=35, db_column='lifeLeaseGrantee')),
                ('residuallandvalue', models.FloatField(db_column='residualLandValue')),
                ('daysonmarket', models.SmallIntegerField(db_column='daysOnMarket')),
                ('datesaleentered', models.DateTimeField(blank=True, null=True, db_column='dateSaleEntered')),
            ],
            options={
                'managed': False,
                'db_table': 'Sales',
            },
        ),
    ]
