# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_parcelmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseMain',
            fields=[
                ('csm_caseno', models.CharField(serialize=False, max_length=14, primary_key=True)),
                ('csm_description', models.TextField(null=True, blank=True)),
                ('csm_target_date', models.DateField(null=True, blank=True)),
                ('csm_expr_date', models.DateField(null=True, blank=True)),
                ('csm_finaled_date', models.DateField(null=True, blank=True)),
                ('csm_issued_date', models.DateField(null=True, blank=True)),
                ('csm_name_first', models.CharField(null=True, max_length=35, blank=True)),
                ('csm_name_last', models.CharField(null=True, max_length=35, blank=True)),
                ('csm_name_mi', models.CharField(null=True, max_length=1, blank=True)),
                ('csm_projname', models.CharField(null=True, max_length=30, blank=True)),
                ('csm_recd_by', models.CharField(null=True, max_length=16, blank=True)),
                ('csm_recd_date', models.DateField(null=True, blank=True)),
                ('csm_status', models.CharField(null=True, max_length=3, blank=True)),
                ('csm_frozen', models.CharField(null=True, max_length=1, blank=True)),
                ('csm_auto_cond', models.CharField(null=True, max_length=3, blank=True)),
                ('csm_updateby', models.CharField(null=True, max_length=4, blank=True)),
                ('csm_updated', models.DateField(null=True, blank=True)),
                ('csm_projno', models.CharField(null=True, max_length=14, blank=True)),
                ('csm_mastno', models.CharField(null=True, max_length=14, blank=True)),
                ('csm_tracking_no', models.BigIntegerField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('case_type', models.CharField(serialize=False, max_length=3, primary_key=True)),
                ('cst_description', models.CharField(null=True, max_length=50, blank=True)),
                ('cst_prcl_flag', models.CharField(null=True, max_length=1, blank=True)),
                ('cst_type', models.CharField(null=True, max_length=1, blank=True)),
                ('cst_sequence', models.IntegerField(null=True, blank=True)),
                ('cst_updateby', models.CharField(null=True, max_length=4, blank=True)),
                ('cst_use_yr', models.CharField(null=True, max_length=1, blank=True)),
                ('cst_year', models.CharField(null=True, max_length=4, blank=True)),
                ('cst_updated', models.DateField(null=True, blank=True)),
                ('cst_fee_date_fld', models.CharField(null=True, max_length=3, blank=True)),
                ('cst_case_dw', models.CharField(null=True, max_length=30, blank=True)),
                ('cst_header_dw', models.CharField(null=True, max_length=30, blank=True)),
                ('cst_exp_date_func', models.CharField(null=True, max_length=35, blank=True)),
                ('cst_exp_date_param', models.CharField(null=True, max_length=80, blank=True)),
                ('cst_summary_rpt', models.CharField(null=True, max_length=50, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('prc_parcel_no', models.CharField(serialize=False, max_length=30, primary_key=True)),
                ('prc_avp_no', models.BigIntegerField()),
                ('prc_vp_no', models.BigIntegerField()),
                ('prc_updated', models.DateField(null=True, blank=True)),
                ('prc_updated_by', models.CharField(null=True, max_length=4, blank=True)),
                ('prc_notes', models.TextField(null=True, blank=True)),
                ('prc_status', models.CharField(null=True, max_length=1, blank=True)),
                ('prc_subdiv', models.CharField(null=True, max_length=50, blank=True)),
                ('prc_lot', models.CharField(null=True, max_length=10, blank=True)),
                ('prc_block', models.CharField(null=True, max_length=5, blank=True)),
                ('prc_quarter', models.CharField(null=True, max_length=2, blank=True)),
                ('prc_section', models.CharField(null=True, max_length=2, blank=True)),
                ('prc_township', models.CharField(null=True, max_length=2, blank=True)),
                ('prc_range', models.CharField(null=True, max_length=2, blank=True)),
                ('prc_zoning', models.CharField(null=True, max_length=5, blank=True)),
                ('prc_census_tract', models.CharField(null=True, max_length=6, blank=True)),
                ('prc_census_blk', models.CharField(null=True, max_length=6, blank=True)),
                ('prc_size', models.DecimalField(null=True, decimal_places=3, max_digits=15, blank=True)),
                ('prc_land_use', models.CharField(null=True, max_length=10, blank=True)),
                ('prc_expt_code', models.CharField(null=True, max_length=3, blank=True)),
                ('prc_fcv_land', models.BigIntegerField(null=True, blank=True)),
                ('prc_fcv_improv', models.IntegerField(null=True, blank=True)),
                ('prc_sale_price', models.DecimalField(null=True, decimal_places=2, max_digits=15, blank=True)),
                ('prc_trnsfr_date', models.DateField(null=True, blank=True)),
                ('prc_legal_desc', models.CharField(null=True, max_length=255, blank=True)),
                ('prc_zip_code', models.CharField(null=True, max_length=10, blank=True)),
                ('prc_township_sfx', models.CharField(null=True, max_length=1, blank=True)),
                ('prc_range_sfx', models.CharField(null=True, max_length=1, blank=True)),
                ('prc_acres', models.CharField(null=True, max_length=2, blank=True)),
                ('prc_legal_lot', models.CharField(null=True, max_length=1, blank=True)),
                ('prc_insp_district', models.CharField(null=True, max_length=4, blank=True)),
                ('prc_cluster_sector', models.CharField(null=True, max_length=4, blank=True)),
                ('prc_prop_class', models.CharField(null=True, max_length=5, blank=True)),
                ('prc_prev_class', models.CharField(null=True, max_length=5, blank=True)),
                ('prc_tax_status', models.CharField(null=True, max_length=30, blank=True)),
                ('prc_prev_tax_status', models.CharField(null=True, max_length=30, blank=True)),
                ('prc_ci_bldg_no', models.BigIntegerField(null=True, blank=True)),
                ('prc_ci_yr_built', models.BigIntegerField(null=True, blank=True)),
                ('prc_ci_flr_area', models.BigIntegerField(null=True, blank=True)),
                ('prc_r_bldg_no', models.BigIntegerField(null=True, blank=True)),
                ('prc_r_yr_built', models.BigIntegerField(null=True, blank=True)),
                ('prc_r_gnd_area', models.BigIntegerField(null=True, blank=True)),
                ('prc_land_map', models.BigIntegerField(null=True, blank=True)),
                ('prc_xstreet1', models.CharField(null=True, max_length=30, blank=True)),
                ('prc_xstreet2', models.CharField(null=True, max_length=30, blank=True)),
                ('prc_mapid', models.BigIntegerField(null=True, blank=True)),
                ('prc_aka_addr', models.CharField(null=True, max_length=50, blank=True)),
                ('prc_nghb_code', models.CharField(null=True, max_length=10, blank=True)),
                ('prc_nsp_code', models.CharField(null=True, max_length=30, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('role_type', models.CharField(serialize=False, max_length=3, primary_key=True)),
                ('role_description', models.CharField(null=True, max_length=50, blank=True)),
                ('role_related_to', models.CharField(null=True, max_length=1, blank=True)),
                ('role_updated', models.DateField(null=True, blank=True)),
                ('role_updateby', models.CharField(null=True, max_length=4, blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='casetype',
            name='role_type',
            field=models.ForeignKey(db_column='role_type', to='assessments.RoleType'),
        ),
        migrations.AddField(
            model_name='casemain',
            name='case_type',
            field=models.ForeignKey(db_column='case_type', related_name='type', to='assessments.CaseType'),
        ),
        migrations.AddField(
            model_name='casemain',
            name='prc_avp_no',
            field=models.ForeignKey(db_column='prc_avp_no', related_name='avp_no', to='assessments.Parcel'),
        ),
        migrations.AddField(
            model_name='casemain',
            name='prc_parcel_no',
            field=models.ForeignKey(db_column='prc_parcel_no', related_name='parcel_no', to='assessments.Parcel'),
        ),
    ]
