# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-17 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_auto_20170519_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pnum', models.CharField(max_length=25)),
                ('caption', models.CharField(max_length=40)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('sketchData', models.ImageField(blank=True, null=True, upload_to='assessments/sketches', verbose_name='sketchData')),
                ('imageData', models.ImageField(blank=True, null=True, upload_to='assessments/images', verbose_name='imageData')),
                ('isPrimarySketch', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'Sketches',
                # 'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='casemain',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='casetype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='parcel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='parcelmaster',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='roletype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'managed': False},
        ),
    ]
