# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-17 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


if settings.RUNNING_UNITTESTS:

    class Migration(migrations.Migration):

        dependencies = [
            ('assessments', '0004_auto_20180417_1235'),
        ]

        operations = [
            migrations.CreateModel(
                name='BSAPARCELDATA',
                fields=[
                    ('PARCELNO', models.CharField(max_length=25)),
                    ('DISTRICT', models.SmallIntegerField()),
                    ('COUNCIL', models.CharField(max_length=25)),
                    ('ECF', models.CharField(max_length=5)),
                    ('PROPADDR', models.CharField(max_length=62)),
                    ('PROPNO', models.FloatField()),
                    ('PROPDIR', models.CharField(max_length=2)),
                    ('PROPSTR', models.CharField(max_length=25)),
                    ('ZIPCODE', models.CharField(max_length=10)),
                    ('TAXPAYER1', models.CharField(max_length=35)),
                    ('TAXPAYER2', models.CharField(max_length=35)),
                    ('TAXPADDR', models.CharField(max_length=35)),
                    ('TAXPCITY', models.CharField(max_length=25)),
                    ('TAXPSTATE', models.CharField(max_length=2)),
                    ('TAXPZIP', models.CharField(max_length=10)),
                    ('propclass', models.CharField(max_length=5)),
                    ('PROPCLASS1', models.CharField(max_length=5)),
                    ('TAXSTATUS', models.CharField(max_length=20)),
                    ('TAXSTATUS1', models.CharField(max_length=20)),
                    ('zoning', models.CharField(max_length=15)),
                    ('TOTALSQFT', models.FloatField()),
                    ('TOTALACREAGE', models.FloatField()),
                    ('FRONTAGE', models.FloatField()),
                    ('DEPTH', models.FloatField()),
                    ('useCode', models.CharField(max_length=5)),
                    ('PRE', models. DecimalField(max_digits=18, decimal_places=0)),
                    ('NEZ', models.CharField(max_length=50)),
                    ('MTT', models.SmallIntegerField()),
                    ('CIBFLAREA', models.FloatField()),
                    ('CIBBLDGNO', models.SmallIntegerField()),
                    ('CIBYRBUILT', models.SmallIntegerField()),
                    ('RESFLAREA', models.IntegerField()),
                    ('RESBLDGNO', models.SmallIntegerField()),
                    ('RESYRBUILT', models.SmallIntegerField()),
                    ('RESSYTLE', models.CharField(max_length=15)),
                    ('ISIMPROVED', models.SmallIntegerField()),
                    ('SALEPRICE', models.FloatField()),
                    ('SALEDATE', models.DateTimeField(null=True)),
                    ('ASV', models.FloatField()),
                    ('ASV1', models.FloatField()),
                    ('TXV', models.DecimalField(max_digits=18, decimal_places=2)),
                    ('TXV1', models.FloatField()),
                    ('SEV', models.FloatField()),
                    ('landvalue', models.FloatField()),
                    ('landMap', models.CharField(max_length=5)),
                    ('RELATED', models.CharField(max_length=25)),
                    ('AKA', models.CharField(max_length=25)),
                    ('SUBDIVISION', models.CharField(max_length=30)),
                    ('RP', models.SmallIntegerField()),
                    ('STATUS', models.CharField(max_length=30)),
                    ('LEGALDESC', models.TextField(null=True)),
                ],
                options={
                    'db_table': 'BSAPARCELDATA',
                },
            ),
        ]
