# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_notifier', '0006_auto_20170504_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='service_notes',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Services Notes'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=32, verbose_name='Subscriber status'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='waste_area_ids',
            field=models.CharField(max_length=64, verbose_name='Subscriber Waste area(s)'),
        ),
    ]
