# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-18 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_account_num', models.IntegerField(verbose_name='Master account number')),
                ('master_account_name', models.CharField(max_length=128, verbose_name='Master account name')),
                ('sub_account_num', models.IntegerField(verbose_name='Sub account number')),
                ('sub_account_name', models.CharField(max_length=128, verbose_name='Sub account name')),
                ('short_name', models.CharField(max_length=128, verbose_name='Short name')),
                ('account_status', models.CharField(max_length=8, verbose_name='Account status')),
                ('group_num', models.IntegerField(verbose_name='Group num')),
                ('item_num', models.IntegerField(db_index=True, verbose_name='Item num (reference num)')),
                ('original_balance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Original balance')),
                ('fed_withholding_tax_this_period', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Fed Withholding tax this period')),
                ('ytd_fed_withholding_tax', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='YTD Fed Withholding tax')),
                ('int_paid_this_period', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Interest paid this period')),
                ('ytd_int_paid', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='YTD interest paid')),
                ('int_split_this_period', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Interest split this period')),
                ('escrow_balance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Escrow balance')),
            ],
        ),
    ]
