# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-19 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowbalance',
            name='master_account_num',
            field=models.BigIntegerField(verbose_name='Master account number'),
        ),
        migrations.AlterField(
            model_name='escrowbalance',
            name='sub_account_num',
            field=models.BigIntegerField(verbose_name='Sub account number'),
        ),
    ]
