# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-19 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_data', '0002_auto_20180719_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowbalance',
            name='item_num',
            field=models.BigIntegerField(db_index=True, verbose_name='Item num (reference num)'),
        ),
    ]
