# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_wizard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteitem',
            name='image_url',
            field=models.URLField(blank=True, default='', verbose_name='Optional image associated with the waste item'),
        ),
        migrations.AlterField(
            model_name='wasteitem',
            name='description',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Waste item description'),
        ),
        migrations.AlterField(
            model_name='wasteitem',
            name='destination',
            field=models.CharField(choices=[('trash', 'Trash'), ('recycling', 'Recycling'), ('bulk', 'Bulk'), ('yard waste', 'Yard Waste'), ('compost', 'Compost')], max_length=32, verbose_name='Appropriate waste destination'),
        ),
        migrations.AlterField(
            model_name='wasteitem',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Keywords associated with the item'),
        ),
        migrations.AlterField(
            model_name='wasteitem',
            name='notes',
            field=models.CharField(blank=True, max_length=300, verbose_name='Special details to note'),
        ),
    ]
