# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_wizard', '0002_auto_20170208_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteitem',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Optional image associated with the waste item'),
        ),
    ]
