# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-07 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20180807_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='district',
            new_name='congress_rep_district',
        ),
        migrations.AddField(
            model_name='poll',
            name='state_rep_district',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='state_senate_district',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
