# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-07 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20180807_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='latitude',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='longitude',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
