# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_survey', '0004_surveyquestionavailanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPropertyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcelno', models.CharField(max_length=32, verbose_name='Parcel ID')),
                ('propaddress', models.CharField(max_length=64, verbose_name='Address')),
                ('propzip', models.CharField(max_length=12, verbose_name='ZIP')),
                ('taxpayer1', models.CharField(max_length=64, verbose_name='Tax Payer 1')),
                ('taxpayer2', models.CharField(max_length=64, verbose_name='Tax Payer 2')),
                ('taxaddr', models.CharField(max_length=64, verbose_name='Tax Payer Address')),
                ('taxcity', models.CharField(max_length=32, verbose_name='Tax Payer City')),
                ('taxstate', models.CharField(max_length=2, verbose_name='Tax Payer State')),
                ('taxzip', models.CharField(max_length=32, verbose_name='Tax Payer ZIP')),
                ('project_co', models.CharField(max_length=32, verbose_name='Project Code')),
                ('ownership', models.CharField(max_length=64, verbose_name='Owner')),
            ],
        ),
    ]
