# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_survey', '0005_publicpropertydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicpropertydata',
            name='parcelno',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Parcel ID'),
        ),
    ]
