# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_survey', '0006_auto_20170717_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestionavailanswer',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Answer Weight'),
        ),
    ]
