# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_survey', '0007_surveyquestionavailanswer_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='scoring_type',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Way to score the answers for the question'),
        ),
    ]
