# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_survey', '0008_surveyquestion_scoring_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Parcel ID')),
                ('house_number', models.IntegerField(blank=True, null=True, verbose_name='House number')),
                ('street_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Street name')),
                ('street_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='Street type')),
                ('zipcode', models.CharField(blank=True, max_length=16, null=True, verbose_name='zipcode')),
            ],
        ),
        migrations.RemoveField(
            model_name='imagemetadata',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='imagemetadata',
            name='parcel_id',
        ),
        migrations.RemoveField(
            model_name='imagemetadata',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='imagemetadata',
            name='street_type',
        ),
        migrations.RemoveField(
            model_name='imagemetadata',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='parcel_id',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='survey_template_id',
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='survy_question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='photo_survey.SurveyQuestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='photo_survey.Survey'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='valid_answers',
            field=models.CharField(help_text='Regex defining valid answers', max_length=256, verbose_name='Valid answers regex'),
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='parcel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='photo_survey.Parcel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='parcel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='photo_survey.Parcel'),
            preserve_default=False,
        ),
    ]
