# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_survey', '0009_auto_20170802_1913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parcel',
            new_name='ParcelMetadata',
        ),
    ]
