# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_survey', '0010_auto_20170802_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyanswer',
            old_name='survy_question',
            new_name='survey_question',
        ),
    ]
