# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_survey', '0011_auto_20170802_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_template_id', models.CharField(db_index=True, max_length=32, verbose_name='Survey name or ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='survey',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='photo_survey.SurveyType'),
            preserve_default=False,
        ),
    ]
