# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_survey', '0012_auto_20170802_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='survey_template_id',
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='photo_survey.SurveyType'),
            preserve_default=False,
        ),
    ]
