# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-29 15:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(max_length=32, verbose_name='Location Type')),
                ('value', models.CharField(max_length=128, verbose_name='Value')),
            ],
        ),
        migrations.AlterField(
            model_name='messengerclient',
            name='description',
            field=models.CharField(max_length=2048, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='messengerclient',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='messengersubscriber',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 15, 18, 40, 620094, tzinfo=utc), verbose_name='Time of initial subscription'),
        ),
        migrations.AlterField(
            model_name='messengersubscriber',
            name='last_status_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 15, 18, 40, 620113, tzinfo=utc), verbose_name='Time of last status change'),
        ),
        migrations.AddField(
            model_name='messengernotification',
            name='locations',
            field=models.ManyToManyField(to='messenger.MessengerLocation'),
        ),
    ]
