# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-05 17:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20190905_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengerlocation',
            name='prefix',
            field=models.CharField(choices=[('dhsem_evac_zone', 'dhsem_evac_zone'), ('zipcode', 'zipcode')], default='citywide', max_length=16, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='messengersubscriber',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 5, 17, 0, 58, 560465, tzinfo=utc), verbose_name='Time of initial subscription'),
        ),
        migrations.AlterField(
            model_name='messengersubscriber',
            name='last_status_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 5, 17, 0, 58, 560483, tzinfo=utc), verbose_name='Time of last status change'),
        ),
    ]
