# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-05 19:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_auto_20190905_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengerlocation',
            name='location_type',
            field=models.CharField(choices=[('DHSEM Evacuation Zone', 'DHSEM Evacuation Zone'), ('ZIP Code', 'ZIP Code'), ('Citywide', 'Citywide')], max_length=32, verbose_name='Location Type'),
        ),
        migrations.AlterField(
            model_name='messengerlocation',
            name='prefix',
            field=models.CharField(choices=[('dhsem_evac_zone', 'dhsem_evac_zone'), ('zipcode', 'zipcode'), ('citywide', 'citywide')], default='citywide', max_length=16, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='messengersubscriber',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 5, 19, 45, 1, 583269, tzinfo=utc), verbose_name='Time of initial subscription'),
        ),
        migrations.AlterField(
            model_name='messengersubscriber',
            name='last_status_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 5, 19, 45, 1, 583287, tzinfo=utc), verbose_name='Time of last status change'),
        ),
    ]
