# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-29 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_auto_20190905_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messengersubscriber',
            name='messenger_client'
        ),
        migrations.AddField(
            model_name='messengersubscriber',
            name='messenger_clients',
            field=models.ManyToManyField(to='messenger.MessengerClient'),
        ),
    ]
