# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessors_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mtttrackerexport2017',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='whd01parcl2017',
            options={'managed': False},
        ),
    ]
